### ISSUE TITLE
mcl update suijisetu出错

### ISSUE THREAD

**Issue by xhzq233** [Ycituss/suijisetu#17]
我按照步骤安装suijisetu后,无法在mirai console里找到suijisetu的命令

status也检测不到suijisetu plugin

所以我尝试mcl install suijisetu

接着upate,then

mcl update suijisetu出错
```
2021-11-14 14:13:00 I/MCL Addon: Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
2021-11-14 14:13:00 I/MCL Addon: Verifying "net.mamoe:mirai-console" v2.8.0
2021-11-14 14:13:00 I/MCL Addon: Verifying "net.mamoe:mirai-console-terminal" v2.8.0
2021-11-14 14:13:00 I/MCL Addon: Verifying "net.mamoe:mirai-core-all" v2.8.0
2021-11-14 14:13:01 I/MCL Addon: Verifying "org.itxtech:mcl-addon" v1.2.2
2021-11-14 14:13:01 I/MCL Addon: Verifying "net.mamoe:chat-command" v0.5.1
2021-11-14 14:13:01 I/MCL Addon: Verifying "io.github.karlatemp:luckperms" v2.5-RC-dev-3+5.3-SNAPSHOT
```
```
2021-11-14 14:30:25 E/MCL Addon: Failed to verify package "suijisetu"
2021-11-14 14:30:25 E/MCL Addon: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.itxtech.mcl.component.Config$Package.getName(Config.java:120)
	at org.itxtech.mcl.component.Config$Package.getBasename(Config.java:124)
	at org.itxtech.mcl.component.Config$Package.getJarFile(Config.java:128)
	at org.itxtech.mcl.Utility.checkLocalFile(Utility.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.addon.MclCommand.run(command.kt:119)
	at org.itxtech.mcl.addon.MclCommand.update(command.kt:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:305)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:163)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:130)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:191)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-11-14 14:30:25 W/MCL Addon: 插件热加载可能导致致命错误，强烈建议重启MCL。

```

**Comment by Ycituss** [comment]
根据报错信息来看似乎并不是我插件的问题，建议重启mcl。
此外本插件指令全部为聊天环境指令，并不能够在console中使用。

**Comment by LittFlower** [comment]
在你的mcl目录下，有一个config.json，就是用来管理插件的，你把那个里面的关于suijisetu的删掉，然后重新加载就好了。再重装suijisetu就行。
